language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
before_install: pip install pipenv
install: pipenv install
script:
  - pip install pylint
  - pylint reposit --rcfile .pylintrc
  - pytest
