language: python
# Python 3.7+ require Ubuntu Xenial (16.04 LTS) or greater
# https://docs.travis-ci.com/user/languages/python/#development-releases-support
dist: xenial
# Existing Python versions
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
matrix:
  allow_failures:
  - python: "3.8-dev"
before_install: pip install pipenv
install: pipenv install
script:
  - pip install pylint
  - pylint reposit --rcfile .pylintrc
  - pip install xenon
  - xenon -b B -m A -a A . 
  - pytest
